### ISSUE TITLE
请问电源部分的BAT电阻的阻值为多少？

### ISSUE THREAD

**Issue by rango42z** [peng-zhihui/MiniRover-Hardware#2]
![image](https://user-images.githubusercontent.com/51521940/99390748-244c5880-2914-11eb-942a-c4cf899a4aa3.png)

**Comment by AllenHarris** [comment]
我也很好奇这个，感觉应该是个肖特基二极管，在立创商城中搜索"BAT“可以搜到肖特基二极管

**Comment by rango42z** [comment]
> 我也很好奇这个，感觉应该是个肖特基二极管，在立创商城中搜索“ BAT”可以搜到肖特基二极管
封装是0805，肖特基二极管没找到0805的封装

**Comment by AllenHarris** [comment]
有SOD-323封装的肖特基二极管，这种封装和0805封装的大小是一样的

**Comment by rango42z** [comment]
> 有SOD-323封装的肖特基二极管，这种封装和0805封装的大小是一样的

🆗，谢谢
